### ISSUE TITLE
The results in this paper are different from those in Kitti

### ISSUE THREAD

**Issue by Xiaohuangya317** [Zengyi-Qin/MonoGRNet#33]
In the paper,when AP3D=0.7, rusults are 13.88 10.19 7.62, running time is 0.06s.  But on KITTI website rusults are 9.61 5.74 4.25, running time is 0.04s.

**Comment by Zengyi-Qin** [comment]
On [KITTI website](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) it wrotes "Note 2: On 08.10.2019, we have followed the suggestions of the Mapillary team in their paper Disentangling Monocular 3D Object Detection and use 40 recall positions instead of the 11 recall positions proposed in the original Pascal VOC benchmark. This results in a more fair comparison of the results, please check their paper. The last leaderboards right before this change can be found here: Object Detection Evaluation, 3D Object Detection Evaluation, Bird's Eye View Evaluation."

**Comment by Zengyi-Qin** [comment]
The numbers in our paper are reported before the change. And it's reported on the val set instead of the test set. Regarding the inference time, you could find that the GPU we used are different. On the website we used Nvidia P40 that is more powerful

**Comment by KunikaValecha** [comment]
How can we test on a dataset other than given in this repo?
